task: validation

data:
  batch_size: 4
  image_size: ${image_size}
  cpu_num: ${cpu_num}
  shuffle: False
  pin_memory: True
  data_augment: {}
  dynamic_shape: False
nms:
  min_confidence: 0.00001
  min_iou: 0.5
  max_bbox: 1000
